# Utiliza una imagen base de PHP con todas las extensiones necesarias para Symfony
FROM php:8.1-fpm-alpine

# Establece el directorio de trabajo
WORKDIR /var/www/html

# Copia el archivo composer.json y ejecuta composer install
COPY composer.json composer.lock ./
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# Copia el resto de los archivos de la aplicación
COPY . .

# Exponer el puerto donde escucha el servidor web
EXPOSE 80

# Comando para iniciar el servidor web
CMD ["php-fpm"]